#!/bin/bash
# Compile check for the Xcode file templates.
#
# Template sources are never built by `swift build` or the test suite, so an
# API change can silently break them. This script substitutes the Xcode
# placeholders and compiles every template against the local package in Swift 6
# language mode, the same way a consuming app would.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PACKAGE_DIR="$(dirname "$SCRIPT_DIR")"
TEMPLATES_DIR="$SCRIPT_DIR/File Templates/SwiftStash"

CHECK_DIR="$(mktemp -d)"
trap 'rm -rf "$CHECK_DIR"' EXIT

SOURCES_DIR="$CHECK_DIR/Sources/TemplateCheck"
mkdir -p "$SOURCES_DIR"

cat > "$CHECK_DIR/Package.swift" <<EOF
// swift-tools-version: 6.2
import PackageDescription

let package = Package(
    name: "TemplateCheck",
    platforms: [.macOS(.v13)],
    dependencies: [
        .package(path: "$PACKAGE_DIR")
    ],
    targets: [
        .target(
            name: "TemplateCheck",
            dependencies: [
                .product(name: "SwiftStash", package: "SwiftStash"),
                .product(name: "SwiftStashUI", package: "SwiftStash")
            ]
        )
    ]
)
EOF

template_count=0
for template_path in "$TEMPLATES_DIR"/*.xctemplate; do
    template_name="$(basename "$template_path" .xctemplate)"
    identifier="${template_name// /}"
    source_file="$template_path/___FILEBASENAME___.swift"

    if [[ ! -f "$source_file" ]]; then
        echo "Missing template source: $source_file" >&2
        exit 1
    fi

    sed -e "s/___FILEBASENAMEASIDENTIFIER___/$identifier/g" \
        -e "s|^//___FILEHEADER___|// $template_name — generated by check.sh|" \
        "$source_file" > "$SOURCES_DIR/$identifier.swift"

    if grep -n '___' "$SOURCES_DIR/$identifier.swift"; then
        echo "Unsubstituted placeholder in template: $template_name" >&2
        exit 1
    fi

    template_count=$((template_count + 1))
done

if [[ "$template_count" -eq 0 ]]; then
    echo "No templates found in: $TEMPLATES_DIR" >&2
    exit 1
fi

swift build --package-path "$CHECK_DIR"

echo "OK — $template_count template(s) compiled against the local package."
